# Generated by Django 3.2.8 on 2024-02-26 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0003_auto_20240226_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saunanfo',
            new_name='SaunaInfo',
        ),
    ]
