# Generated by Django 3.2.8 on 2024-03-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0004_rename_saunanfo_saunainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('sauna_id', models.IntegerField()),
            ],
        ),
    ]
